### ISSUE TITLE
Is PlunderBox still in Development?

### ISSUE THREAD

**Issue by Rekulous** [juaneth/PlunderBox#1]
I've been following this repo for a while and so far I've only seen one commit and the Discord server got deleted, is it still in development, cancelled, or something else?

**Comment by zgal88** [comment]
Likely cancelled. User "jumped ship" shortly after this repo and the server created.

**Comment by Rekulous** [comment]
> Likely cancelled. User "jumped ship" shortly after this repo and the server was created.

Oof, that sucks because this could've been an alternative to Vapor Store

**Comment by zgal88** [comment]
> > Likely cancelled. User "jumped ship" shortly after this repo and the server was created.
> 
> Oof, that sucks because this could've been an alternative to Vapor Store

Yep, it looked like a decent idea. I actually only ran across this repo, because I was looking to make something similar. Still not sure about the idea, but if I do, I'll try to remember to come back to this repo, to link to it.

**Comment by juan-crackhead** [comment]
I stopped development because of school, im still working on it but im not sure if its gonna be worked on lots, my friend closed the discord because he's an ass and had access to my account

**Comment by Rekulous** [comment]
> I stopped development because of school, im still working on it but im not sure if its gonna be worked on lots, my friend closed the discord because he's an ass and had access to my account

That's awesome! Its sorta still in development, and now I see why the Discord shut down. Thanks for clarifying

**Comment by juaneth** [comment]
I am restarting development and I'm moving the whole thing to a new name and theme, i'll be posting updates on my twitter https://twitter.com/juanppmaster
